version: '3.7'
services:
  db:
    image: mysql:latest
    hostname: hrmgt_db_host
    restart: always
    environment:
      MYSQL_DATABASE: hrmgt_database
      MYSQL_USER: hrmgt_admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
    ports:
      - '3306:3306'
    volumes:  
      - db_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '8080:80'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
